### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by msmuenchen** [srijs/rusha#10]
Hi,

I'm having problems using rusha for comparing a string in Javascript with the same string hashed in PHP.

In Javascript, I use

    var sha=new Rusha(); sha.digest("\u00e4")
    "7e5c0f7aba32cf3e22fd30c4513a21e6d1c3aeff"

and in PHP (once using a literal ä, once a json-decode'd ä to rule out a bug in PHP or my file encoding)

    $c1="ä";
    $c2=json_decode("\"\\u00e4\"");
    echo "1: -$c1- 2: -$c2-\n";
    echo json_encode($c1)."\n";
    echo json_encode($c2)."\n";
    
    echo sha1($c1)."\n";
    echo sha1($c2)."\n";

which gives me the output

    1: -ä- 2: -ä-
    "\u00e4"
    "\u00e4"
    961fa22f61a56e19f3f5f8867901ac8cf5e6d11f
    961fa22f61a56e19f3f5f8867901ac8cf5e6d11f

Why are the SHA1 hashes different? After all, using the \u00e4 notation should result in the same byte sequence both in a PHP string and a Javascript string, right?

**Comment by szydan** [comment]
@sergeevabc in case you still need it - from the documentation (readme) 
"Create a hex digest from a binary String. A binary string is expected to only contain characters whose charCode < 256"

So the library will not work on arbitrary strings 
The workaround I found for your case is to first convert your utf-8 encoded string to byte array and then pass it to rusha. See the code below:
```
function toUTF8Array(str) {
    var utf8 = [];
    for (var i=0; i < str.length; i++) {
        var charcode = str.charCodeAt(i);
        if (charcode < 0x80) utf8.push(charcode);
        else if (charcode < 0x800) {
            utf8.push(0xc0 | (charcode >> 6),
                      0x80 | (charcode & 0x3f));
        }
        else if (charcode < 0xd800 || charcode >= 0xe000) {
            utf8.push(0xe0 | (charcode >> 12),
                      0x80 | ((charcode>>6) & 0x3f),
                      0x80 | (charcode & 0x3f));
        }
        // surrogate pair
        else {
            i++;
            // UTF-16 encodes 0x10000-0x10FFFF by
            // subtracting 0x10000 and splitting the
            // 20 bits of 0x0-0xFFFFF into two halves
            charcode = 0x10000 + (((charcode & 0x3ff)<<10)
                      | (str.charCodeAt(i) & 0x3ff));
            utf8.push(0xf0 | (charcode >>18),
                      0x80 | ((charcode>>12) & 0x3f),
                      0x80 | ((charcode>>6) & 0x3f),
                      0x80 | (charcode & 0x3f));
        }
    }
    return utf8;
}

var r = new Rusha();
var s = "любовь"
var a = toUTF8Array(s)
console.log(r.digest(a));  //will give you the correct sha1 af48c12732ffdbd4299b792c2b6da6f77a0898d7
```

**Comment by sergeevabc** [comment]
Thanks for your input, @szydan. At that time I chose [Fast SHA256](github.com/dchest/fast-sha256-js).

**Comment by srijs** [comment]
Closing this as wontfix -- Rusha is not meant to be used directly on encoded strings with code-points above 255. If you want to hash strings like these, please be sure to convert them into the desired binary encoding beforehand.
