### ISSUE TITLE
Uncaught TypeError: Cannot read property 'byteLength' of undefined rusha.js:282

### ISSUE THREAD

**Issue by fernandoc1** [srijs/rusha#15]
Hi,

I'm receiving the following error, when passing an ArrayBuffer to rusha.js

Uncaught TypeError: Cannot read property 'byteLength' of undefined rusha.js:282

Here is the code that I'm using:
https://gist.github.com/fernandoc1/79ee1d0721c399519fa5

Would someone help me finding what is going wrong?

**Comment by srijs** [comment]
The behaviour causing the problems here can now be disabled via `Rusha.disableWorkerBehaviour()`. Closing.
