### ISSUE TITLE
grunt-contrib-connect should be dev dependency?

### ISSUE THREAD

**Issue by dominictarr** [srijs/rusha#21]
This is making npm install take ages but isn't actually used in the code. I'm guessing someone accidentially did a `npm install <module> -S` instead of `npm install <module> -D`
https://github.com/srijs/rusha/blob/master/package.json#L48

**Comment by srijs** [comment]
Oh, yeah, absolutely. Thanks!

**Comment by ArtskydJ** [comment]
Could this change be published to npm?

**Comment by srijs** [comment]
rusha 0.8.1 published to npm.
