### ISSUE TITLE
segfault in node.js

### ISSUE THREAD

**Issue by dominictarr** [srijs/rusha#22]
It seems totally strange that this could be happening in js, but I'm getting a segfault with this in node.js

I have been benchmarking js hash implementations and before 0.7.8 rusha does very very well,
but with 0.7.8 or 0.8.0 it gets a segfault!

clone this repo: https://github.com/dominictarr/crypto-bench
and run npm install

then I get this output:

```  node bench-hash.js rusha
run (N), input-size (bytes), ops (bytes/ms), time (ms)
1, 1, 8.17, 0.12239902080783353
3, 2, 31.24, 0.06402048655569782
5, 3, 31.71, 0.0946073793755913
7, 4, 32.48, 0.12315270935960591
Segmentation fault (core dumped)
```
this does create many hashes in quick succession... maybe that is related?

**Comment by srijs** [comment]
Hi Dominic,

I can't reproduce the issue. Can you give me more detail on which platform and node version you are running?

Cheers, Sam.

**Comment by dominictarr** [comment]
archlinux, node@0.10.31

okay I upgraded to 0.10.34 and now it doesn't happen.
