### ISSUE TITLE
Wrong hash for files of 512Mb or more

### ISSUE THREAD

**Issue by ldwedari** [srijs/rusha#23]
Rusha produces wrong hash values for files with sizes greater or equal 512MB.

Rusha is not meant to have any kind of limitation in terms of file sizes, so this is definitely a bug in Rusha, or a limitation of the underlying system.

The fact that up to 511MB everything works fine might point to some of the padding or conversion calculations not being correct, since the "core" rusha routine is being run for every chunk (64K by default) in the same manner, and I wouldn't expect it to suddenly work differently.
Note: I've tested it with chunk sizes of 16bk ans 2Mb, being the result incorrect, too.

**Comment by tguyard** [comment]
I've experienced the same bug.
It seems to be a problem on int32 overflow when applying the final padding.

**Comment by srijs** [comment]
Fixed by https://github.com/srijs/rusha/pull/26

**Comment by srijs** [comment]
Fix published as part of rusha 0.8.2

**Comment by ldwedari** [comment]
Tested OK. Thanks!
