### ISSUE TITLE
Wrong hash when hashing close to 1GB

### ISSUE THREAD

**Issue by kalley** [srijs/rusha#29]
I couldn't track down the exact spot where I started getting problems, but it's very close to 1GB.

This is tested against node's crypto library as well as c#'s hashing (which are both the same).

I'm digging around in the SHA1 spec, but I don't really have that kind of background.

**Comment by srijs** [comment]
Hi, and thanks for filing this bug. Before I start investigating this, could you please provide me with:

- The version of rusha you are using
- The way you were running it (node.js, or browser (webworker or ui thread))
- The way you supplied the input (ArrayBuffer, string, etc.)

**Comment by kalley** [comment]
Using version 0.8.2 in the browser (web worker).

Passing a `File` object.

**Comment by srijs** [comment]
Did you test with multiple browsers, or just one? Which versions?

**Comment by kalley** [comment]
These all generate the same (wrong) hash:
Firefox version 36.0.4
Chrome version 43.0.2357.81

I'm testing in IE in a VM right now, which is super slow, so I'll update if it's the same when that's finished.

If it helps, I've been testing with zip files, uploaded using either a file input or drag and drop. There is no difference between using either of source of input.

**Comment by srijs** [comment]
This should be fixed in version 0.8.4.
