### ISSUE TITLE
Broken on Firefox 31 with browserify

### ISSUE THREAD

**Issue by feross** [srijs/rusha#30]
When using `Rusha` with browserify, `Rusha._core` is undefined and gives the following error:

```
TypeError: Rusha._core is not a constructor
```

On [this line](https://github.com/srijs/rusha/blob/d3d7d742a26ff9e673f15f2946b4bbcf5f792bab/rusha.js#L230).

Here's my guess as to what's going on:

In a commonJS environment `Rusha` is not put on the `window`, which is [expected](https://github.com/srijs/rusha/blob/d3d7d742a26ff9e673f15f2946b4bbcf5f792bab/rusha.js#L387-L388). The line that's referring to `Rusha._core` should still work because the function is named `Rusha` and code inside a function can refer to that function if it has a name. But for some reason, this doesn't seem to happen in Firefox when ASM is enabled.

To solve this, could we just put `Rusha._core` in a local variable named `Core` and refer to that to fix this in Firefox?

Tested on Firefox 31. ASM may have improved on newer versions to fix this bug.

**Comment by srijs** [comment]
Sounds like a plausible fix to me. Do you want to submit a PR?

**Comment by feross** [comment]
Sorry, I don't have time at the moment.

**Comment by srijs** [comment]
Testing via browserify in a newer Firefox version, this seems to no longer occur. Closing.
