### ISSUE TITLE
Please update bower

### ISSUE THREAD

**Issue by chafey** [srijs/rusha#33]
The current version in bower is outdated, can you please keep it up to date with the NPM version or remove support for bower?  I spent several hours trying to figure out why I was getting different hashes in my node app vs the browser app and it turned out that the bower version was older and had a bug with Uint8Arrays that had a byteOffset on the underlying ArrayBuffer.  Thanks

**Comment by srijs** [comment]
Sure thing! Sorry for not keeping the bower version up to date. I will update it within the next hours.

**Comment by srijs** [comment]
I just cut the 0.8.3 release here, which I confirmed to be picked up by bower: https://github.com/srijs/rusha/releases/tag/v0.8.3

Sorry again for the pain this caused you, I'll make sure to push all git tags going forward.

**Comment by chafey** [comment]
Thanks for the quick response!
