### ISSUE TITLE
Intercepting service worker messages

### ISSUE THREAD

**Issue by xuset** [srijs/rusha#39]
I'm using a package in a service worker that has rusha somewhere in it's dependency tree, and something I noticed is that rusha is attaching itself to the 'message' event in the service worker and tries to hash every message that it receives. Is this on purpose and if so is there a way to disable this?

As a side note, service workers don't have `postMessage` defined globally so every time a message is sent to the worker an exception is raised when rusha handles the event.

**Comment by srijs** [comment]
This is likely related to #15. I would be open to accept a pull request to disable the "automagic" worker behaviour in Rusha, if you can think of a good way.

**Comment by xuset** [comment]
That issue seems to be exactly what I've encountered, thanks!

I have a few ideas on how to go about it, let me know what you think. A possible idea is moving the worker code to separate file. Using the worker code could be done like: `new Worker('rusha-worker.js')`. This would require that the core rusha code be imported in the worker script, or alternatively the worker code could be bundled/packed with something like browserify so the worker script wouldn't need to import anything.

Another approach being, leave the worker code where it is, but only hash received messages if they contain some magic number/string that is unique to rusha. So only messages that were intended for rusha actually get hashed.

I think both approaches have their merits. Any thoughts?
