### ISSUE TITLE
Message handling throws ReferenceError in shared and service workers

### ISSUE THREAD

**Issue by xuset** [srijs/rusha#44]
Shared workers and service workers do not have `postMessage` defined in their global scope so when they receive a message and attempt to call `postMessage` a ReferenceError is thrown.

Maybe it's best to only attach the message listener if the global scope is of type `DedicatedWorkerGlobalScope`?

**Comment by srijs** [comment]
Fixed. Now we will only attempt handling messages when inside a dedicated web worker!
