### ISSUE TITLE
Typings on DefinitelyTyped

### ISSUE THREAD

**Issue by jacoscaz** [srijs/rusha#59]
Hello!

I've just opened a PR to add typings for this library over at DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49123.

If you're still working on this, would you be able to review my PR?

**Comment by srijs** [comment]
Hi @jacoscaz, great to see you adding typings to DT! I've looked at the PR you linked, and the types look good to me 👍
