### ISSUE TITLE
Resumable hash operation possible?

### ISSUE THREAD

**Issue by iosc82** [srijs/rusha#60]
The Readme says to use the `Hash` API, but does that expose `getState`/`setState`?
Is there currently a way to use this library in order to resume a previous hash operation?

```
rusha = require('rusha');
const hasher = new rusha.createHash();
console.log(hasher.getState()); // fails with Uncaught TypeError: hasher.getState is not a function
```

**Comment by srijs** [comment]
Hi yeah, you can use the `.state` prop as documented here: https://github.com/srijs/rusha#properties. Feel free to reopen if you have any other questions!

**Comment by iosc82** [comment]
Thanks for your kind response, I actually missed that line in the Readme! However, I still can't seem to make it work (using rusha 0.8.13, Node v12.22.1).

The following code assumes a file `myfile` to be present. `hasher.state` is `undefined`, where I'd expect some state representation:

```
rusha = require('rusha');
fs = require('fs');

const hasher = new rusha.createHash();
const input = fs.createReadStream('myfile');

input.on('readable', function() {
    const chunk = this.read();

    if (chunk) {
        hasher.update(chunk);
        console.log(hasher.state);
    }
});
```

**Comment by srijs** [comment]
Oh, haha, looks like that's my bad :)

Apparently I never published after adding this property. I just pushed version 0.8.14 which should include the code to support this!

**Comment by iosc82** [comment]
Yes, that solved it for me! Thank you very much!
